services:
  uncompromised_dev:
    build:
      dockerfile: DockerfileLocal
    container_name: uncompromised_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    volumes:
      - .:/code
      - uncompromised_backend:/code/node_modules
      - .env:/code/.env
    networks:
      - uncompromised_network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - uncompromised_postgres:/var/lib/postgresql/data
    networks:
      - uncompromised_network

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - uncompromised_redis:/data
    networks:
      - uncompromised_network

volumes:
  uncompromised_backend:
  uncompromised_postgres:
  uncompromised_redis:

networks:
  uncompromised_network:
    driver: bridge
